apiVersion: v1
kind: LimitRange
metadata:
    name: limitrange-devops
    namespace: devops
spec:
    limits:
    - default:
        cpu: 200m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      type: Container
