kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-devops
  namespace: devops
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-devops
  namespace: devops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-devops
subjects:
- kind: Group
  namespace: devops
  name: 1dfda5b9-a05c-4056-b2cd-ceb446dd232e

