apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myrs
   annotations:
      description: "this is app"
spec:
   replicas: 3
   selector:
      matchExpressions:
      - key: app
        operator: In
        values: [myapp]
      - key: env
        operator: Exists

   template:
      metadata:
         labels:
            app: myapp
            env: prod
      spec:
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80

---

