apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mydb
  name: mydb-pod
spec:
  containers:
  - name: con1
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test123
    - name: MYSQL_DATABASE
      value: wordpress

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  ports:
  - port: 3306
  selector:
    app: mydb

