apiVersion: apps/v1
kind: Deployment
metadata:
   name: mydep-liv-exec
spec:
   replicas: 2
   selector:
      matchLabels:
         app: myapp
   template:
      metadata:
         labels:
            app: myapp
      spec:
        containers:
        - name: con1
          image: nginx:latest
          ports:
          - containerPort: 80
            #          livenessProbe:
            #             tcpSocket:
            #               port: 8080
            #             initialDelaySeconds: 10
            #             periodSeconds: 5
          readinessProbe:
             httpGet:
               path: /
               port: 8080
             initialDelaySeconds: 10
             periodSeconds: 5

---
---
apiVersion: v1
kind: Service
metadata:
  name: mypod-svc
spec:
#  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: myapp

