apiVersion: v1
kind: Pod
metadata:
  name: adapter
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}
  containers:
  - name: main-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do date > /var/log/top.txt && top -n 1 -b >> /var/log/top.txt; sleep 10;done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log
  - name: adapter-container
    image: alpine
    command: ["/bin/sh"]
    args: ["-c", "while true; do (cat /var/log/top.txt | head -4 >> /var/log/status.txt | tail -1); sleep 10; done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /var/log

